SELECT * FROM Customer

--Q1. What is the total revenue generated by male vs. female customers?
SELECT
	gender,
	SUM(purchase_amount) AS revenue
FROM Customer
GROUP BY gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT
	customer_id,
	purchase_amount
FROM Customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
						SELECT AVG(purchase_amount)
						FROM Customer
						)


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5
	item_purchased,
	ROUND(AVG(review_rating),2) AS avg_product_rating
FROM Customer
GROUP BY item_purchased
ORDER BY avg_product_rating DESC


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT
	shipping_type,
	ROUND(AVG(purchase_amount),2) AS average_purchase
FROM Customer
GROUP BY shipping_type
HAVING shipping_type IN ('Standard','Express')


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT 
	subscription_status,
	COUNT(customer_id) AS total_customer,
	AVG(purchase_amount) AS average_spend,
	SUM(purchase_amount) AS total_revenue
FROM Customer
GROUP BY subscription_status


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
	item_purchased,
	SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)*100/COUNT(*) AS percentage_purchased
FROM Customer
GROUP BY item_purchased
ORDER BY percentage_purchased DESC


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
(SELECT
	'New' AS customer_type,
	COUNT(*) AS total_customers,
	SUM(previous_purchases) AS number_of_purchases
FROM Customer
WHERE previous_purchases = 1)
UNION
(SELECT
	'Returning',
	COUNT(*),
	SUM(previous_purchases)
FROM Customer
WHERE previous_purchases BETWEEN 2 AND 10)
UNION
(SELECT
	'Loyal',
	COUNT(*),
	SUM(previous_purchases)
FROM Customer
WHERE previous_purchases > 10)


--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
SELECT
	category,
	item_purchased,
	COUNT(customer_id) AS total_orders,
	ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank

FROM customer
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
	subscription_status,
	COUNT(customer_id) AS repeat_buyers
FROM Customer
WHERE previous_purchases > 5
GROUP BY subscription_status


--Q10. What is the revenue contribution of each age group? 
SELECT
	age_group,
	SUM(purchase_amount) AS total_revenue
FROM Customer
GROUP BY age_group
ORDER BY total_revenue DESC
